export const control_conv = {
	'1': 'Public',
	'2': 'Private For-Profit',
	'3': 'Private Nonprofit',
	'4': 'Private Nonprofit (religious)',
	'-1': 'Not reported',
};

export const high_deg_conv = {
	'11': 'Doctorate',
	'12': 'Doctorate',
	'13': 'Doctorate',
	'14': 'Doctorate',
	'20': "Master's",
	'30': "Bachelor's",
	'40': "Associate's",
	'0': 'Non-degree granting',
	'-3': '{Not available}',
};

export const locale_conv = {
	'11': 'City: Large',
	'12': 'City: Midsize',
	'13': 'City: Small',
	'21': 'Suburb: Large',
	'22': 'Suburb: Midsize',
	'23': 'Suburb: Small',
	'31': 'Town: Fringe',
	'32': 'Town: Distant',
	'33': 'Town: Remote',
	'41': 'Rural: Fringe',
	'42': 'Rural: Distant',
	'43': 'Rural: Remote',
	'-3': 'Not available',
};

export const state_conv = {
	AK: 'Alaska',
	AL: 'Alabama',
	AR: 'Arkansas',
	AS: 'American Samoa',
	AZ: 'Arizona',
	CA: 'California',
	CO: 'Colorado',
	CT: 'Connecticut',
	DC: 'District of Columbia',
	DE: 'Delaware',
	FL: 'Florida',
	FM: 'Federated States of Micronesia',
	GA: 'Georgia',
	GU: 'Guam',
	HI: 'Hawaii',
	IA: 'Iowa',
	ID: 'Idaho',
	IL: 'Illinois',
	IN: 'Indiana',
	KS: 'Kansas',
	KY: 'Kentucky',
	LA: 'Louisiana',
	MA: 'Massachusetts',
	MD: 'Maryland',
	ME: 'Maine',
	MH: 'Marshall Islands',
	MI: 'Michigan',
	MN: 'Minnesota',
	MO: 'Missouri',
	MP: 'Northern Mariana Islands',
	MS: 'Mississippi',
	MT: 'Montana',
	NC: 'North Carolina',
	ND: 'North Dakota',
	NE: 'Nebraska',
	NH: 'New Hampshire',
	NJ: 'New Jersey',
	NM: 'New Mexico',
	NV: 'Nevada',
	NY: 'New York',
	OH: 'Ohio',
	OK: 'Oklahoma',
	OR: 'Oregon',
	PA: 'Pennsylvania',
	PR: 'Puerto Rico',
	PW: 'Palau',
	RI: 'Rhode Island',
	SC: 'South Carolina',
	SD: 'South Dakota',
	TN: 'Tennessee',
	TX: 'Texas',
	UT: 'Utah',
	VA: 'Virginia',
	VI: 'Virgin Islands',
	VT: 'Vermont',
	WA: 'Washington',
	WI: 'Wisconsin',
	WV: 'West Virginia',
	WY: 'Wyoming',
};
